version: "3"

services:
  postgres:
    image: arminc/clair-db:latest
    restart: unless-stopped
    networks:
      - net_clair
    ports:
      - 5432:5432

  clair:
    image: arminc/clair-local-scan:v2.0.8_fe9b059d930314b54c78f75afe265955faf4fdc1
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - 6060:6060
    volumes:
      - /tmp:/tmp
    command: [-config, /config/config.yaml]
    networks:
      - net_clair

networks:
  net_clair:
